import React from "react";

function WhyChooseUs() {
  return (
    <section className="section section-l" id="features">
      <div className="container">
        <div className="row justify-content-center text-center">
          <div className="col-lg-6">
            <div className="section-head section-head-s2">
              <h2
                className="title title-xl animated"
                data-animate="fadeInUp"
                data-delay="0.1"
                title="Our Features"
              >
                Why Choose Us?
              </h2>
              <p className="animated" data-animate="fadeInUp" data-delay="0.2">
                Mega Trade Villa ?
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="container container-xxl">
        <div className="nk-block">
          <div className="row align-items-center justify-content-center justify-content-xl-between gutter-vr-30px">
            <div className="col-xxl-6 col-xl-6 col-lg-8">
              <div
                className="nk-block-img nk-block-plx animated"
                data-animate="fadeInUp"
                data-delay="0.3"
              >
                <img
                  className="shadow rounded"
                  src="images/app-screens/sc-medium-b.png"
                  alt=""
                />
                <img
                  className="nk-block-img-plx plx-screen shadow rounded"
                  src="images/app-screens/sc-small-d.jpg"
                  alt=""
                />
                <img
                  className="nk-block-img-plx plx-circle plx-circle-s1"
                  src="images/gfx/circle-a.png"
                  alt=""
                />
                <img
                  className="nk-block-img-plx plx-polygon plx-polygon-s1"
                  src="images/gfx/polygon-a.png"
                  alt=""
                />
                <img
                  className="nk-block-img-plx plx-triangle plx-triangle-s1"
                  src="images/gfx/triangle-a.png"
                  alt=""
                />
              </div>
            </div>
            <div className="col-xxl-5 col-xl-6 col-lg-8">
              <div className="nk-block-text">
                <div
                  className="feature feature-inline animated"
                  data-animate="fadeInUp"
                  data-delay="0.4"
                >
                  <div className="feature-icon feature-icon-md">
                    <em className="icon icon-xs icon-circle fas fa-check" />
                  </div>
                  <div className="feature-text">
                    <p>Mega Trade Villa is completely free of charge!</p>
                  </div>
                </div>
                <div
                  className="feature feature-inline animated"
                  data-animate="fadeInUp"
                  data-delay="0.5"
                >
                  <div className="feature-icon feature-icon-md">
                    <em className="icon icon-xs icon-circle fas fa-check" />
                  </div>
                  <div className="feature-text">
                    <p>
                      Mega Trade Villa can help you trade in both the manual and
                      automatic formats with an average of 87.35% Win Rate
                      across all compatible brokers.
                    </p>
                  </div>
                </div>
                <div
                  className="feature feature-inline animated"
                  data-animate="fadeInUp"
                  data-delay="0.6"
                >
                  <div className="feature-icon feature-icon-md">
                    <em className="icon icon-xs icon-circle fas fa-check" />
                  </div>
                  <div className="feature-text">
                    <p>
                      Mega Trade Villa is fully SSL and highly secure thereby
                      providing little or no chance for your personal details to
                      be phished by cyber-criminals.
                    </p>
                  </div>
                </div>
                <div
                  className="feature feature-inline animated"
                  data-animate="fadeInUp"
                  data-delay="0.7"
                >
                  <div className="feature-icon feature-icon-md">
                    <em className="icon icon-xs icon-circle fas fa-check" />
                  </div>
                  <div className="feature-text">
                    <p>
                      Our signals are generated by a complex set of mathematical
                      operations involving the indicators and the method you’ve
                      selected for trading.
                    </p>
                  </div>
                </div>
                <div
                  className="feature feature-inline animated"
                  data-animate="fadeInUp"
                  data-delay="0.8"
                >
                  <div className="feature-icon feature-icon-md">
                    <em className="icon icon-xs icon-circle fas fa-check" />
                  </div>
                  <div className="feature-text">
                    <p>
                      Mega Trade Villa can be synced with the Top-Class brokers
                      in the market providing you with security for your capital
                      and a peace of mind.
                    </p>
                  </div>
                </div>
                <div
                  className="text-center text-sm-left animated"
                  data-animate="fadeInUp"
                  data-delay="0.9"
                >
                  <a href="Meg-Villa/" className="btn">
                    Get Started
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default WhyChooseUs;
